[workspace]

members = [
  "filecoin-proofs",
  "storage-proofs-core",
  "storage-proofs-porep",
  "storage-proofs-post",
  "fil-proofs-tooling",
  "fil-proofs-param",
  "fr32",
  "sha2raw",
  "filecoin-hashers",
  "storage-proofs-update",
  "fil-proofs-bin",
]

[patch.crates-io]
neptune = { git = "https://github.com/vmx/neptune", branch = "pc2-perf" }
rust-gpu-tools = { git = "https://github.com/filecoin-project/rust-gpu-tools", branch = "pc2-perf" }
